name: Azure - Delete Terraform Backend

on:
  workflow_dispatch:

env:
  TF_VAR_RESOURCE_GROUP_NAME: ${{ vars.TF_VAR_RESOURCE_GROUP_NAME }}
  TF_VAR_STORAGE_ACCOUNT_NAME: ${{ vars.TF_VAR_STORAGE_ACCOUNT_NAME }}

jobs:
  Destroy_Terraform_Backend_Storage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.49.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/infrastructure/backend/azure/delete-tf-backend.sh
            $GITHUB_WORKSPACE/infrastructure/backend/azure/delete-tf-backend.sh
